repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    default_language_version:
    python: python3.7
    hooks:
    -   id: check-case-conflict
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
